# Permalinks
permalink:           /:year/:month/:title

# Setup
title:               "The Frenzy"
tagline:             "Home for the latest news!"
url:                 http://rahil.shivjiani.com
paginate:            10
baseurl:             ""
analytics_id:        ""

# About/contact
author:
  name:              "R Shivjiani"
  url:               http://rahil.shivjiani.com
  email:             ""

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


########################
#                      #
# ADDED CUSTOM         #
#                      #
########################

# List of pages
pages_list:
  about: '/about'
  archives: '/archives'
  contact: '/contact'
  subscribe: '/subscribe'

# Fix date/time generation
timezone: America/New_York

# Custom excerpt
excerpt_separator: <!--more-->

########################
#                      #
#  END CUSTOM          #
#                      #
########################
